AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-target-blank.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
