language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
before_install:
  - gem update --system
  - gem install bundler
script: scripts/cibuild
sudo: false
cache: bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
